# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  hostBuildPath: '/pipelines-dotnet-core.csproj'
  dotnetConfig: ' -c Release -f netcoreapp2.1 -o $(Build.ArtifactStagingDirectory)' 

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '5c232253-c9fa-4d61-b145-4432b44a6ef0'
    includeNuGetOrg: false
- task: DotNetCoreCLI@2 # 预定义的task,使用dotnet进行发布编译
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '$(hostBuildPath) $(dotnetConfig)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1 # 预定义的task
  displayName: 'publish artifact: drop'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

